// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./../components/base-button/BaseButton.vue')['default']
    BaseHamburger: typeof import('./../components/base-hamburger/BaseHamburger.vue')['default']
    BaseImage: typeof import('./../components/base-image/BaseImage.vue')['default']
    BaseThemeToggle: typeof import('./../components/base-theme-toggle/BaseThemeToggle.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    'IconBi:github': typeof import('~icons/bi/github')['default']
    'IconGg:menuLeft': typeof import('~icons/gg/menu-left')['default']
    'IconIc:outlineLightMode': typeof import('~icons/ic/outline-light-mode')['default']
    'IconMaterialSymbols:contentCopyOutline': typeof import('~icons/material-symbols/content-copy-outline')['default']
    'IconMaterialSymbols:keyboardDoubleArrowRight': typeof import('~icons/material-symbols/keyboard-double-arrow-right')['default']
    'IconMaterialSymbols:nightlight': typeof import('~icons/material-symbols/nightlight')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./../components/the-footer/TheFooter.vue')['default']
    TheNavigation: typeof import('./../components/TheNavigation.vue')['default']
    TheSidebar: typeof import('./../components/TheSidebar.vue')['default']
  }
}

export {}
