// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./../components/base-button/BaseButton.vue')['default']
    BaseHamburger: typeof import('./../components/base-hamburger/BaseHamburger.vue')['default']
    BaseImage: typeof import('./../components/base-image/BaseImage.vue')['default']
    BaseThemeToggle: typeof import('./../components/base-theme-toggle/BaseThemeToggle.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./../components/the-footer/TheFooter.vue')['default']
    TheNavigation: typeof import('./../components/the-navigation/TheNavigation.vue')['default']
    TheSidebar: typeof import('./../components/the-sidebar/TheSidebar.vue')['default']
  }
}

export {}
